const BASE_URL = "https://www.aqbeds.com";

function normalizeImages(images) {
  return images.map((img) => (img.startsWith("http") ? img : `${BASE_URL}${img}`));
}

const PRODUCTS_CATALOG = [
  {
    id: "ambessador",
    slug: "ambessador",
    name: "Luxury Ambessador Bed",
    description:
      "Your bedroom's new centrepiece — with a secret. The Ambessador pairs a deep-buttoned, hand-finished headboard with a solid timber frame you'll never hear creak. Choose crushed or plush velvet in 16 colours, then add gas-lift ottoman storage that swallows duvets, suitcases and everything else you'd rather not look at. Every Ambessador includes a comfort mattress free — so it's sleep-ready the day it arrives. Free UK delivery · 30-day returns · 1-year warranty · Pay on delivery available.",
    basePrice: 360,
    originalPrice: 400,
    category: "luxury-beds",
    stock: 24,
    images: [
      "/all products img/Ambessador/1.webp",
      "/all products img/Ambessador/2.webp",
      "/all products img/Ambessador/3.webp",
      "/all products img/Ambessador/4.webp",
    ],
  },
  {
    id: "arizona",
    slug: "arizona",
    name: "Luxury Arizona Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 250,
    originalPrice: 300,
    category: "luxury-beds",
    stock: 24,
    images: [
      "/all products img/Arizona/1.webp",
      "/all products img/Arizona/2.webp",
      "/all products img/Arizona/3.webp",
      "/all products img/Arizona/4.webp",
    ],
  },
  {
    id: "bunk-beds",
    slug: "bunk-beds",
    name: "Bunk Bed",
    description: "Sturdy metal bunk bed, available in Double or Trio configuration. Choice of Gray or White finish.",
    basePrice: 449,
    originalPrice: 500,
    category: "ottoman-beds",
    stock: 24,
    images: [
      "/all products img/Bunk beds/1.webp",
      "/all products img/Bunk beds/2.webp",
      "/all products img/Bunk beds/3.webp",
      "/all products img/Bunk beds/4.webp",
    ],
  },
  {
    id: "divan",
    slug: "divan",
    name: "Luxury Divan Bed",
    description: "Our Luxury Divan base with custom headboard options. Choose from Panel, Simple, Cube or the premium Chesterfield design. Optional drawer storage available.",
    basePrice: 185,
    originalPrice: 200,
    category: "divan-beds",
    stock: 24,
    images: [
      "/all products img/Divan/1 Panel line head board.webp",
      "/all products img/Divan/2 simple plain head board.webp",
      "/all products img/Divan/3 Cube head board.webp",
      "/all products img/Divan/4 Chesterfiled head board.webp",
    ],
  },
  {
    id: "divan-ottoman-bed",
    slug: "divan-ottoman-bed",
    name: "Aurora Ottoman Gas-Lift Bed",
    description:
      'A full storage room hiding under your mattress. One hand, one motion: the gas-lift base rises to reveal a full-width cavity — bedding, suitcases, winter coats, gone. Built on a solid timber frame with a 45" standard headboard (54" available), upholstered in 16 velvet and chenille shades, and delivered free with a mattress included from £350. Free UK delivery · 30-day returns · 1-year warranty · Pay on delivery available.',
    basePrice: 350,
    originalPrice: 400,
    category: "ottoman-beds",
    stock: 24,
    images: [
      "/all products img/Divan Ottoman bed/1.webp",
      "/all products img/Divan Ottoman bed/2.webp",
      "/all products img/Divan Ottoman bed/3.webp",
      "/all products img/Divan Ottoman bed/4.webp",
    ],
  },
  {
    id: "florida-bed",
    slug: "florida-bed",
    name: "Luxury Florida Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 210,
    originalPrice: 250,
    category: "luxury-beds",
    stock: 24,
    images: [
      "/all products img/Florida bed/1.webp",
      "/all products img/Florida bed/2.webp",
      "/all products img/Florida bed/3.webp",
      "/all products img/Florida bed/4.webp",
    ],
  },
  {
    id: "golden-wave-bed",
    slug: "golden-wave-bed",
    name: "Luxury Golden Wave Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 250,
    originalPrice: 300,
    category: "luxury-beds",
    stock: 24,
    images: [
      "/all products img/Golden wave bed/1.webp",
      "/all products img/Golden wave bed/2.webp",
      "/all products img/Golden wave bed/3.webp",
      "/all products img/Golden wave bed/4.webp",
    ],
  },
  {
    id: "hilton",
    slug: "hilton",
    name: "Luxury Hilton Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 210,
    originalPrice: 250,
    category: "luxury-beds",
    stock: 24,
    images: [
      "/all products img/Hilton/1.webp",
      "/all products img/Hilton/2.webp",
      "/all products img/Hilton/3.webp",
      "/all products img/Hilton/4.webp",
    ],
  },
  {
    id: "luxury-cube-bed",
    slug: "luxury-cube-bed",
    name: "Luxury Cube Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 210,
    originalPrice: 250,
    category: "luxury-beds",
    stock: 24,
    images: [
      "/all products img/Luxury Cube bed/1.webp",
      "/all products img/Luxury Cube bed/2.webp",
      "/all products img/Luxury Cube bed/3.webp",
      "/all products img/Luxury Cube bed/4.webp",
    ],
  },
  {
    id: "oxford-wingback",
    slug: "oxford-wingback",
    name: "Luxury Oxford Wingback Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 250,
    originalPrice: 300,
    category: "luxury-beds",
    stock: 24,
    images: [
      "/all products img/Oxford Wingback/1.webp",
      "/all products img/Oxford Wingback/2.webp",
      "/all products img/Oxford Wingback/3.webp",
      "/all products img/Oxford Wingback/4.webp",
    ],
  },
  {
    id: "panel-line",
    slug: "panel-line",
    name: "Luxury Panel Line Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 210,
    originalPrice: 250,
    category: "luxury-beds",
    stock: 24,
    images: [
      "/all products img/Panel Line/1.webp",
      "/all products img/Panel Line/2.webp",
      "/all products img/Panel Line/3.webp",
      "/all products img/Panel Line/aiwatermarkremover_be829fcc2ddf69fa20c08c939c63482c.webp",
    ],
  },
  {
    id: "panel-line-bumper",
    slug: "panel-line-bumper",
    name: "Luxury Panel Line Bumper Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 210,
    originalPrice: 250,
    category: "luxury-beds",
    stock: 24,
    images: [
      "/all products img/Panel line bumper/1.webp",
      "/all products img/Panel line bumper/2.webp",
      "/all products img/Panel line bumper/3.webp",
      "/all products img/Panel line bumper/1000154119-clean.webp",
    ],
  },
  {
    id: "panel-line-gold-strip",
    slug: "panel-line-gold-strip",
    name: "Luxury Panel Line Gold Strip Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 250,
    originalPrice: 300,
    category: "luxury-beds",
    stock: 24,
    images: [
      "/all products img/Panel line gold strip/1.webp",
      "/all products img/Panel line gold strip/2.webp",
      "/all products img/Panel line gold strip/3.webp",
      "/all products img/Panel line gold strip/4.webp",
    ],
  },
  {
    id: "panel-wing-back",
    slug: "panel-wing-back",
    name: "Luxury Panel Wing Back Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 210,
    originalPrice: 250,
    category: "luxury-beds",
    stock: 24,
    images: [
      "/all products img/Panel wing back/1.webp",
      "/all products img/Panel wing back/2.webp",
      "/all products img/Panel wing back/3.webp",
      "/all products img/Panel wing back/4.webp",
    ],
  },
  {
    id: "sleigh",
    slug: "sleigh",
    name: "Luxury Sleigh Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 250,
    originalPrice: 300,
    category: "luxury-beds",
    stock: 24,
    images: [
      "/all products img/Sleigh/1.webp",
      "/all products img/Sleigh/2.webp",
      "/all products img/Sleigh/3.webp",
      "/all products img/Sleigh/4.webp",
    ],
  },
  {
    id: "alina-wardrobe",
    slug: "alina-wardrobe",
    name: "Alina Wardrobe",
    description: "The Alina Wardrobe offers versatile storage with multiple door and drawer configurations. From compact 2-door units to massive 8-door sets, customize it with mirrors and chests to fit your room perfectly.",
    basePrice: 150,
    originalPrice: 220,
    category: "wardrobes",
    stock: 24,
    images: [
      "/Wardrobes/alina-wardrobe-main.webp",
      "/Wardrobes/alina-wardrobe-gallery-1.webp",
      "/Wardrobes/alina-wardrobe-gallery-2.webp",
      "/Wardrobes/alina-wardrobe-gallery-3.webp",
    ],
  },
  {
    id: "sliding-wardrobe",
    slug: "sliding-wardrobe",
    name: "Sliding Wardrobe",
    description: "Modern Sliding Wardrobe with glass or mirror accents. A perfect space-saver for contemporary bedrooms. Available in widths from 100cm to 250cm with optional professional assembly.",
    basePrice: 260,
    originalPrice: 320,
    category: "sliding-wardrobes",
    stock: 24,
    images: [
      "/Sliding wardrobe/sliding-wardrobe-main.webp",
      "/Sliding wardrobe/sliding-wardrobe-gallery-1.webp",
      "/Sliding wardrobe/sliding-wardrobe-gallery-2.webp",
      "/Sliding wardrobe/sliding-wardrobe-gallery-3.webp",
    ],
  },
  {
    id: "alaska-sofa",
    slug: "alaska-sofa",
    name: "Alaska Sofa",
    description: "Premium handcrafted Alaska Sofa, customized for luxury and comfort.",
    basePrice: 280,
    originalPrice: 310,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Alaska Sofaa/alaska-sofa-main.webp",
      "/Sofas/Alaska Sofaa/alaska-sofa-gallery-1.webp",
      "/Sofas/Alaska Sofaa/alaska-sofa-gallery-2.webp",
      "/Sofas/Alaska Sofaa/alaska-sofa-gallery-3.webp",
    ],
  },
  {
    id: "ashton-sofa",
    slug: "ashton-sofa",
    name: "Ashton Sofa",
    description: "Premium handcrafted Ashton Sofa, customized for luxury and comfort.",
    basePrice: 300,
    originalPrice: 350,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Ashton Sofa/ashton-sofa-main.webp",
      "/Sofas/Ashton Sofa/ashton-sofa-gallery-1.webp",
      "/Sofas/Ashton Sofa/ashton-sofa-gallery-2.webp",
      "/Sofas/Ashton Sofa/ashton-sofa-gallery-3.webp",
    ],
  },
  {
    id: "berlin-sofa-bed",
    slug: "berlin-sofa-bed",
    name: "Berlin Sofa bed",
    description: "Premium handcrafted Berlin Sofa bed, customized for luxury and comfort.",
    basePrice: 380,
    originalPrice: 400,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Berlin Sofa Bed/berlin-sofa-bed-main.webp",
      "/Sofas/Berlin Sofa Bed/berlin-sofa-bed-gallery-1.webp",
      "/Sofas/Berlin Sofa Bed/berlin-sofa-bed-gallery-2.webp",
      "/Sofas/Berlin Sofa Bed/berlin-sofa-bed-gallery-3.webp",
    ],
  },
  {
    id: "chesterfield-sofa",
    slug: "chesterfield-sofa",
    name: "Chesterfield Sofa",
    description: "Premium handcrafted Chesterfield Sofa, customized for luxury and comfort.",
    basePrice: 370,
    originalPrice: 400,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Chesterfield Sofa/chesterfield-sofa-main.webp",
      "/Sofas/Chesterfield Sofa/chesterfield-sofa-gallery-1.webp",
      "/Sofas/Chesterfield Sofa/chesterfield-sofa-gallery-2.webp",
      "/Sofas/Chesterfield Sofa/chesterfield-sofa-gallery-3.webp",
    ],
  },
  {
    id: "diamontee-sofa",
    slug: "diamontee-sofa",
    name: "Diamontee Sofa",
    description: "Premium handcrafted Diamontee Sofa, customized for luxury and comfort.",
    basePrice: 280,
    originalPrice: 300,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Diamontee sofa/diamontee-sofa-main.webp",
      "/Sofas/Diamontee sofa/diamontee-sofa-gallery-1.webp",
      "/Sofas/Diamontee sofa/diamontee-sofa-gallery-2.webp",
    ],
  },
  {
    id: "dino-sofa",
    slug: "dino-sofa",
    name: "Dino Sofa",
    description: "Premium handcrafted Dino Sofa, customized for luxury and comfort.",
    basePrice: 280,
    originalPrice: 320,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Dino sofa/dino-sofa-main.webp",
      "/Sofas/Dino sofa/dino-sofa-gallery-1.webp",
      "/Sofas/Dino sofa/dino-sofa-gallery-2.webp",
      "/Sofas/Dino sofa/dino-sofa-gallery-3.webp",
    ],
  },
  {
    id: "dylan-sofa",
    slug: "dylan-sofa",
    name: "Dylan Sofa",
    description: "Premium handcrafted Dylan Sofa, customized for luxury and comfort.",
    basePrice: 185,
    originalPrice: 220,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Dylan Sofa/dylan-sofa-main.webp",
      "/Sofas/Dylan Sofa/dylan-sofa-gallery-1.webp",
      "/Sofas/Dylan Sofa/dylan-sofa-gallery-2.webp",
      "/Sofas/Dylan Sofa/dylan-sofa-gallery-3.webp",
    ],
  },
  {
    id: "harrison-sofa",
    slug: "harrison-sofa",
    name: "Harrison Sofa",
    description: "Premium handcrafted Harrison Sofa, customized for luxury and comfort.",
    basePrice: 310,
    originalPrice: 350,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Harrison Sofa/harrison-sofa-main.webp",
      "/Sofas/Harrison Sofa/harrison-sofa-gallery-1.webp",
      "/Sofas/Harrison Sofa/harrison-sofa-gallery-2.webp",
      "/Sofas/Harrison Sofa/harrison-sofa-gallery-3.webp",
    ],
  },
  {
    id: "lily-sofa",
    slug: "lily-sofa",
    name: "Lily Sofa",
    description: "Premium handcrafted Lily Sofa, customized for luxury and comfort.",
    basePrice: 310,
    originalPrice: 350,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Lily Sofa/lily-sofa-main.webp",
      "/Sofas/Lily Sofa/lily-sofa-gallery-1.webp",
      "/Sofas/Lily Sofa/lily-sofa-gallery-2.webp",
      "/Sofas/Lily Sofa/lily-sofa-gallery-3.webp",
    ],
  },
  {
    id: "lucca-anton-sofa-bed",
    slug: "lucca-anton-sofa-bed",
    name: "Lucca & Anton Sofa Bed",
    description: "Premium handcrafted Lucca & Anton Sofa Bed, customized for luxury and comfort.",
    basePrice: 650,
    originalPrice: 700,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Lucca & Anton Sofa Bed/lucca-anton-sofa-bed-main.webp",
      "/Sofas/Lucca & Anton Sofa Bed/lucca-anton-sofa-bed-gallery-1.webp",
      "/Sofas/Lucca & Anton Sofa Bed/lucca-anton-sofa-bed-gallery-2.webp",
      "/Sofas/Lucca & Anton Sofa Bed/lucca-anton-sofa-bed-gallery-3.webp",
    ],
  },
  {
    id: "maya-sofa",
    slug: "maya-sofa",
    name: "Maya sofa",
    description: "Premium handcrafted Maya sofa, customized for luxury and comfort.",
    basePrice: 280,
    originalPrice: 320,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Maya Sofa/maya-sofa-main.webp",
      "/Sofas/Maya Sofa/maya-sofa-gallery-1.webp",
      "/Sofas/Maya Sofa/maya-sofa-gallery-2.webp",
      "/Sofas/Maya Sofa/maya-sofa-gallery-3.webp",
    ],
  },
  {
    id: "olympia-sofa",
    slug: "olympia-sofa",
    name: "Olympia sofa",
    description: "Premium handcrafted Olympia sofa, customized for luxury and comfort.",
    basePrice: 280,
    originalPrice: 320,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Olympia Sofa/olympia-sofa-main.webp",
      "/Sofas/Olympia Sofa/olympia-sofa-gallery-1.webp",
      "/Sofas/Olympia Sofa/olympia-sofa-gallery-2.webp",
      "/Sofas/Olympia Sofa/olympia-sofa-gallery-3.webp",
    ],
  },
  {
    id: "shanon-sofa",
    slug: "shanon-sofa",
    name: "Shanon Sofa",
    description: "Premium handcrafted Shanon Sofa, customized for luxury and comfort.",
    basePrice: 280,
    originalPrice: 320,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Shanon Sofa/shanon-sofa-main.webp",
      "/Sofas/Shanon Sofa/shanon-sofa-gallery-1.webp",
      "/Sofas/Shanon Sofa/shanon-sofa-gallery-2.webp",
      "/Sofas/Shanon Sofa/shanon-sofa-gallery-3.webp",
    ],
  },
  {
    id: "u-shape-sofa",
    slug: "u-shape-sofa",
    name: "U shape Sofa",
    description: "Premium handcrafted U shape Sofa, customized for luxury and comfort.",
    basePrice: 590,
    originalPrice: 620,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/U Shape Sofa/u-shape-sofa-main.webp",
      "/Sofas/U Shape Sofa/u-shape-sofa-gallery-1.webp",
      "/Sofas/U Shape Sofa/u-shape-sofa-gallery-2.webp",
      "/Sofas/U Shape Sofa/u-shape-sofa-gallery-3.webp",
    ],
  },
  {
    id: "verona-sofa",
    slug: "verona-sofa",
    name: "Verona Sofa",
    description: "Premium handcrafted Verona Sofa, customized for luxury and comfort.",
    basePrice: 280,
    originalPrice: 320,
    category: "sofas",
    stock: 24,
    images: [
      "/Sofas/Verona Sofa/verona-sofa-main.webp",
      "/Sofas/Verona Sofa/verona-sofa-gallery-1.webp",
      "/Sofas/Verona Sofa/verona-sofa-gallery-2.webp",
      "/Sofas/Verona Sofa/verona-sofa-gallery-3.webp",
    ],
  },
];

module.exports = { PRODUCTS_CATALOG, BASE_URL, normalizeImages };
