const BASE_URL = "https://www.aqbeds.com";

function normalizeImages(images) {
  return images.map((img) => (img.startsWith("http") ? img : `${BASE_URL}${img}`));
}

const PRODUCTS_CATALOG = [
  {
    id: "ambessador",
    slug: "ambessador",
    name: "Luxury Ambessador Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 360,
    originalPrice: 400,
    category: "luxury-beds",
    stock: 24,
    images: ["/all products img/Ambessador/1.webp", "/all products img/Ambessador/2.webp", "/all products img/Ambessador/3.webp"],
  },
  {
    id: "victoria",
    slug: "victoria",
    name: "Victoria Ottoman Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 320,
    originalPrice: 380,
    category: "ottoman-beds",
    stock: 18,
    images: ["/all products img/Victoria/1.webp", "/all products img/Victoria/2.webp", "/all products img/Victoria/3.webp"],
  },
  {
    id: "georgian",
    slug: "georgian",
    name: "Georgian Divan Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 280,
    originalPrice: 340,
    category: "divan-beds",
    stock: 22,
    images: ["/all products img/Georgian/1.webp", "/all products img/Georgian/2.webp", "/all products img/Georgian/3.webp"],
  },
  {
    id: "queen-anne",
    slug: "queen-anne",
    name: "Queen Anne Storage Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 340,
    originalPrice: 400,
    category: "storage-beds",
    stock: 15,
    images: ["/all products img/Queen Anne/1.webp", "/all products img/Queen Anne/2.webp", "/all products img/Queen Anne/3.webp"],
  },
  {
    id: "elizabeth",
    slug: "elizabeth",
    name: "Elizabeth Luxury Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 420,
    originalPrice: 500,
    category: "luxury-beds",
    stock: 12,
    images: ["/all products img/Elizabeth/1.webp", "/all products img/Elizabeth/2.webp", "/all products img/Elizabeth/3.webp"],
  },
  {
    id: "henry",
    slug: "henry",
    name: "Henry Ottoman Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 300,
    originalPrice: 360,
    category: "ottoman-beds",
    stock: 20,
    images: ["/all products img/Henry/1.webp", "/all products img/Henry/2.webp", "/all products img/Henry/3.webp"],
  },
  {
    id: "edward",
    slug: "edward",
    name: "Edward Divan Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 260,
    originalPrice: 320,
    category: "divan-beds",
    stock: 25,
    images: ["/all products img/Edward/1.webp", "/all products img/Edward/2.webp", "/all products img/Edward/3.webp"],
  },
  {
    id: "william",
    slug: "william",
    name: "William Storage Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 310,
    originalPrice: 370,
    category: "storage-beds",
    stock: 17,
    images: ["/all products img/William/1.webp", "/all products img/William/2.webp", "/all products img/William/3.webp"],
  },
  {
    id: "charles",
    slug: "charles",
    name: "Charles Luxury Bed",
    description: "Includes Standard Comfort Mattress (FREE) and a premium handcrafted headboard. Built in the UK with the finest materials for a royal sleep experience.",
    basePrice: 380,
    originalPrice: 450,
    category: "luxury-beds",
    stock: 14,
    images: ["/all products img/Charles/1.webp", "/all products img/Charles/2.webp", "/all products img/Charles/3.webp"],
  },
  {
    id: "dylan-sofa",
    slug: "dylan-sofa",
    name: "Dylan Sofa",
    description: "Premium handcrafted sofa made in the UK with luxury fabrics and superior comfort.",
    basePrice: 899,
    originalPrice: 1100,
    category: "sofas",
    stock: 8,
    images: ["/Sofas/Dylan Sofa/dylan-sofa-main.webp", "/Sofas/Dylan Sofa/dylan-sofa-2.webp"],
  },
];

module.exports = { PRODUCTS_CATALOG, BASE_URL, normalizeImages };