import manifest from "./responsive-images.json";

type ResponsiveAttrs = { src: string; srcSet?: string };

function variantPath(path: string, width: number): string {
  const dot = path.lastIndexOf(".");
  if (dot === -1) return `${path}-${width}.webp`;
  return `${path.slice(0, dot)}-${width}.webp`;
}

/**
 * Returns src/srcSet attributes for a public image when responsive variants
 * have been generated by `npm run responsive-images`.
 * Images without variants fall back to a plain src.
 */
export function responsiveSrc(path: string): ResponsiveAttrs {
  const widths = (manifest as Record<string, number[]>)[path];
  if (!widths || widths.length < 2) return { src: path };
  return {
    src: path,
    srcSet: widths.map((w) => `${variantPath(path, w)} ${w}w`).join(", "),
  };
}
